version: '3.4'

services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  eshopmicroservice.catalog.api:
    image: ${DOCKER_REGISTRY-}eshopmicroservicecatalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/EShopMicroservice.Catalog.Api/Dockerfile

  eshopmicroservice.basket.api:
    image: ${DOCKER_REGISTRY-}eshopmicroservicebasketapi
    build:
      context: .
      dockerfile: src/Services/Basket/EShopMicroservice.Basket.Api/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:



