version: '3.4'

services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  orderdb:
    image: mcr.microsoft.com/mssql/server

  distributedcache:
    image: redis

  messagebroker:
    image: rabbitmq:management

  eshopmicroservice.catalog.api:
    image: ${DOCKER_REGISTRY-}eshopmicroservicecatalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/EShopMicroservice.Catalog.Api/Dockerfile

  eshopmicroservice.basket.api:
    image: ${DOCKER_REGISTRY-}eshopmicroservicebasketapi
    build:
      context: .
      dockerfile: src/Services/Basket/EShopMicroservice.Basket.Api/Dockerfile

  eshopmicroservice.discount.grpc:
    image: ${DOCKER_REGISTRY-}eshopmicroservicediscountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/EShopMicroservice.Discount.Grpc/Dockerfile

  eshopmicroservice.ordering.api:
    image: ${DOCKER_REGISTRY-}eshopmicroserviceorderingapi
    build:
      context: .
      dockerfile: src/Services/Ordering/EShopMicroservice.Ordering.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  mssql_order:





